# Site settings
title: Ari Summer
description: >
  Blog about software and life.


baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hitchhiker.ma" # the base hostname & protocol for your site

author:
  fullname: Ari Summer
  github: summera
  twitter: summ3ra

  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown
